packages:
  - "packages/*"
  - "test/deployment/*"
  - "workers/*"

autoInstallPeers: false
engineStrict: true
minimumReleaseAge: 4320
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
