/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=TokenExchangeEnv src/env.generated.d.ts` (hash: 2c78b0c4ce1eb5b45b7e7b1094a7085b)
interface __BaseEnv_TokenExchangeEnv {
  TOKEN_EXCHANGE_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./generic-worker");
  }
  interface Env extends __BaseEnv_TokenExchangeEnv {}
}
interface TokenExchangeEnv extends __BaseEnv_TokenExchangeEnv {}
