/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=TokenExchangeEnv src/env.generated.d.ts` (hash: ca948b40b0e91c3dde42dbf62d8709f9)
interface __BaseEnv_TokenExchangeEnv {
	TOKEN_EXCHANGE_RATE_LIMIT: RateLimit;
	GITHUB_API_BASE_URL: "https://api.github.com";
	GITHUB_APP_ID: "000000";
	TOKEN_BROKER_AUDIENCE: "https://broker.example";
	GITHUB_APP_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./generic-worker");
	}
	interface Env extends __BaseEnv_TokenExchangeEnv {}
}
interface TokenExchangeEnv extends __BaseEnv_TokenExchangeEnv {}
