export const testGitHubUserAccount = {
  avatar_url: "https://avatars.githubusercontent.com/u/67890?v=4",
  events_url: "https://api.github.com/users/fixture-owner/events{/privacy}",
  followers_url: "https://api.github.com/users/fixture-owner/followers",
  following_url: "https://api.github.com/users/fixture-owner/following{/other_user}",
  gists_url: "https://api.github.com/users/fixture-owner/gists{/gist_id}",
  gravatar_id: null,
  html_url: "https://github.com/fixture-owner",
  id: 67890,
  login: "fixture-owner",
  node_id: "U_fixture",
  organizations_url: "https://api.github.com/users/fixture-owner/orgs",
  received_events_url: "https://api.github.com/users/fixture-owner/received_events",
  repos_url: "https://api.github.com/users/fixture-owner/repos",
  site_admin: false,
  starred_url: "https://api.github.com/users/fixture-owner/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/fixture-owner/subscriptions",
  type: "User",
  url: "https://api.github.com/users/fixture-owner",
};

export const testGitHubEnterpriseAccount = {
  avatar_url: "https://avatars.githubusercontent.com/enterprises/fixture-enterprise",
  created_at: "2026-01-01T00:00:00Z",
  html_url: "https://github.com/enterprises/fixture-enterprise",
  id: 67890,
  name: "Fixture Enterprise",
  node_id: "E_fixture",
  slug: "fixture-enterprise",
  updated_at: "2026-01-01T00:00:00Z",
};

export const testGitHubAppResponse = {
  created_at: "2026-01-01T00:00:00Z",
  description: "Fixture GitHub App",
  events: ["push"],
  external_url: "https://example.test/fixture-app",
  html_url: "https://github.com/apps/fixture-app",
  id: 2419473,
  name: "Fixture App",
  node_id: "A_fixture",
  owner: testGitHubUserAccount,
  permissions: { metadata: "read" },
  slug: "fixture-app",
  updated_at: "2026-01-01T00:00:00Z",
};

export const testGitHubInstallationResponse = {
  account: testGitHubUserAccount,
  access_tokens_url: "https://api.github.com/app/installations/12345/access_tokens",
  app_id: 2419473,
  app_slug: "fixture-app",
  created_at: "2026-01-01T00:00:00Z",
  events: ["push"],
  html_url: "https://github.com/settings/installations/12345",
  id: 12345,
  permissions: { metadata: "read" },
  repositories_url: "https://api.github.com/installation/repositories",
  repository_selection: "all",
  single_file_name: null,
  suspended_at: null,
  suspended_by: null,
  target_id: 67890,
  target_type: "User",
  updated_at: "2026-01-01T00:00:00Z",
};
